### ISSUE TITLE
When deploying app, the ReportViewer shows an error "AkiReport.trdp not found"

### ISSUE THREAD

**Issue by LanceMcCarthy** [atanaka1591/ResumeProject#1]
Nice job so far, everything works as expected when deployed from Visual Studio to localhost.

However, when deploying the project, I observed a problem with the report. This is a great opportunity to experience a real-world issue that you might get a call/ticket for.

## Problem

When publishing to the project to any real location (IIS, Azure, etc), there appears to be missing content/files that are required by the project.

![image](https://user-images.githubusercontent.com/3520532/162969715-1a84c6d3-cd10-4a28-be32-87bb0aba706f.png)

### Investigation Hint

When this ReportViewer is loaded, it tells the REST API "Hey, I want to view AkiReport.trdp". The REST service then tries to find that file in `/Reports/` folder, but it is not there in the server environment and returns the error.

#### Next Steps

What are the most common reasons why a file might be missing from a published web app?

Also just as important, if the TRDP file is there, but any data source files are not (i.e. a csv file the report is expecting), you'll have a similar problem. The same solution you might apply to fix the other missing file might also be the same solution for this.

> Hint:  The fix for this is literally a couple clicks, no code involved.

## Solution

I'll leave it to you to investigate this further and we can discuss what you did later. If you do have a solution, you can push an update to the repo and update this Issue (_reply to this issue as if you're replying to a customer who opened the Issue_).

> It is important to know when to leverage your resources (e.g., docs, demos, and most importantly.. _people_). No one person knows everything, an investigator needs to know their current limits and what resources are available to them and when use those resources. Trying to do everything on your own can lead to lots of wasted time and frustration 😎 To see that this is a fixable problem, here's your project in an Azure hosted environment => https://uiforblazor.azurewebsites.net/. 

### Unrelated Note

There seems to be a `master` and a `main` branch in this repo. The project code is currently committed to the master branch, but not the default main branch. This can happen when a repo was initialized locally and then pushed to GitHub later (most services do not use the 'master' naming anymore, instead it's just main), I suspect this might be the reason for the incongruity. 

It's not a big deal, but if you did want to fix it and simplify the repo, it can be fixed by:

- Merging master into main and then deleting master
  - or
- Go into the repository's Settings tab > Branches panel and change the default branch to master

**Comment by atanaka1591** [comment]
Thank you for the detailed reply, Lance! Apologies for the late reply -
it's been quite a hectic week here. I believe I needed to add the Reports
folder with the TRDP file to the wwwroot folder and also point to that
directory in the ConfigureServices method in Startup.cs. Definitely a good
call on leaning into my available resources aka YOU and your team.
Sometimes I can get tunnel-vision with my stubbornness in trying to figure
things out on my own.. something I'm working on. I look forward to our
meeting tomorrow!

Aki

**Comment by LanceMcCarthy** [comment]
Fixed in #3
